#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MasterDetail.Resource", IsApplication=true)]

namespace MasterDetail
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public const int backgroundSrc = 2130771985;
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f010010
			public const int thumbnailSrc = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int title = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_dark_background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_light_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_shadow_end_color = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cardview_shadow_start_color = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public const int cardview_compat_inset_shadow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int cardview_default_elevation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int cardview_default_radius = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_border_right = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_border_transparent = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_content_create = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_content_save = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_copy_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_cut_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_paste_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_search_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int journey0 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int journey1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int journey10 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int journey2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int journey3 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int journey4 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int journey5 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int journey6 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int journey7 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int journey8 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int journey9 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int round_layout = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int shape = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int trash = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int BirthdayEditFragment = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int BirthdayLabel = 2131034133;
			
			// aapt resource value: 0x7f05001e
			public const int BirthdayTextView = 2131034142;
			
			// aapt resource value: 0x7f050002
			public const int DetailFragmentContainer = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int Email = 2131034145;
			
			// aapt resource value: 0x7f050018
			public const int EmailEditFragment = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int EmailLabel = 2131034135;
			
			// aapt resource value: 0x7f05001f
			public const int EmailTextView = 2131034143;
			
			// aapt resource value: 0x7f050012
			public const int FirstameEditFragment = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int FirstameLabel = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int FragmentContainerPersonDetail = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int LastnameEditFragment = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int LastnameLabel = 2131034131;
			
			// aapt resource value: 0x7f050022
			public const int MainToolbar = 2131034146;
			
			// aapt resource value: 0x7f050020
			public const int Name = 2131034144;
			
			// aapt resource value: 0x7f05001c
			public const int NameLabel = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int NameTextView = 2131034141;
			
			// aapt resource value: 0x7f050006
			public const int People = 2131034118;
			
			// aapt resource value: 0x7f050023
			public const int PeopleMenuAdd = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int PeopleMenuPreferences = 2131034148;
			
			// aapt resource value: 0x7f050005
			public const int PeopleToolbar = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int PersonCardBackground = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int PersonCardDelete = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int PersonCardEdit = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int PersonCardEmail = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int PersonCardFirstName = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int PersonCardFirstNameLabel = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int PersonCardImage = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int PersonCardLastName = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int PersonCardLastNameLabel = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int PersonCardName = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int PersonHeader = 2131034115;
			
			// aapt resource value: 0x7f050019
			public const int PersonHeaderBackgorund = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int PersonHeaderThumbnail = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int PersonHeaderTitle = 2131034138;
			
			// aapt resource value: 0x7f050025
			public const int PersonMenuDelete = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int PersonMenuEdit = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int PersonMenuSave = 2131034150;
			
			// aapt resource value: 0x7f050001
			public const int RecyclerView = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CardRecycler = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Detail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PersonCardView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PersonEditFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PersonHeader = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PersonShowFragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RowItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int toolbar = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int PeopleMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int PersonMenu = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public const int AppTheme = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int Base_CardView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardView_Light = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] PersonHeader = new int[] {
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 2
			public const int PersonHeader_backgroundSrc = 2;
			
			// aapt resource value: 1
			public const int PersonHeader_thumbnailSrc = 1;
			
			// aapt resource value: 0
			public const int PersonHeader_title = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
